name: FallenGodTestament
version: 1.7.0
main: com.fallengod.testament.Testament
api-version: 1.21
author: FallenGod Development Team
description: Epic Minecraft plugin where players collect divine fragments to unlock ultimate powers

commands:
  summondragon:
    description: Summon the custom Ender Dragon boss
    usage: /summondragon [player]
    permission: testament.summon.dragon
    permission-message: You don't have permission to summon the dragon!

permissions:
  testament.summon.dragon:
    description: Allows summoning the custom Ender Dragon
    default: op
  testament.admin:
    description: Full admin access to all Testament features
    default: op
    children:
      - testament.summon.dragon